### ISSUE TITLE
Add ability to configure json-file output location

### ISSUE THREAD

**Issue by xblitz** [chef-cookbooks/audit#286]
### Cookbook version
current

### Chef-client version
any

### Scenario:
Using the audit cookbook with file base output, we cannot choose the location and name of the file

**Comment by chris-rock** [comment]
Thank you for the feedback, right now filenames are auto-generated, as we see here: https://github.com/chef-cookbooks/audit/blob/master/files/default/handler/audit_report.rb#L260-L262

It would be nice to have the same feature-set as in test-kitchen:
```
verifier:
  name: inspec
  format: junit
  output: path/to/results/%{platform}_%{suite}_inspec.xml
```

see https://github.com/chef/kitchen-inspec#usage
